version: "3.9"

services:
  app:
    build: .
    container_name: app
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      - db
  
  db:
    image: postgres:14
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"            # expose to host
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
